# Generated by Django 4.0.1 on 2022-01-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_is_active_alter_coupon_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='used',
            new_name='use_count',
        ),
    ]
