# Generated by Django 4.0.1 on 2022-01-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_rename_used_coupon_use_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='use_count',
            new_name='num_used',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
    ]
