# Generated by Django 4.0.1 on 2022-01-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_rename_use_count_coupon_num_used_remove_coupon_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
